// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.2
// source: cosmos/msg/v1/msg.proto

/* eslint-disable */

export const protobufPackage = "cosmos.msg.v1";
