// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v5.29.2
// source: shentu/bounty/v1/bounty.proto

/* eslint-disable */
import Long from "long";
import _m0 from "protobufjs/minimal";
import { Coin } from "../../../cosmos/base/v1beta1/coin";
import { Duration } from "../../../google/protobuf/duration";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "shentu.bounty.v1";

export enum ProgramStatus {
  PROGRAM_STATUS_INACTIVE = 0,
  PROGRAM_STATUS_ACTIVE = 1,
  PROGRAM_STATUS_CLOSED = 2,
  UNRECOGNIZED = -1,
}

export function programStatusFromJSON(object: any): ProgramStatus {
  switch (object) {
    case 0:
    case "PROGRAM_STATUS_INACTIVE":
      return ProgramStatus.PROGRAM_STATUS_INACTIVE;
    case 1:
    case "PROGRAM_STATUS_ACTIVE":
      return ProgramStatus.PROGRAM_STATUS_ACTIVE;
    case 2:
    case "PROGRAM_STATUS_CLOSED":
      return ProgramStatus.PROGRAM_STATUS_CLOSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProgramStatus.UNRECOGNIZED;
  }
}

export function programStatusToJSON(object: ProgramStatus): string {
  switch (object) {
    case ProgramStatus.PROGRAM_STATUS_INACTIVE:
      return "PROGRAM_STATUS_INACTIVE";
    case ProgramStatus.PROGRAM_STATUS_ACTIVE:
      return "PROGRAM_STATUS_ACTIVE";
    case ProgramStatus.PROGRAM_STATUS_CLOSED:
      return "PROGRAM_STATUS_CLOSED";
    case ProgramStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum SeverityLevel {
  SEVERITY_LEVEL_UNSPECIFIED = 0,
  SEVERITY_LEVEL_CRITICAL = 1,
  SEVERITY_LEVEL_HIGH = 2,
  SEVERITY_LEVEL_MEDIUM = 3,
  SEVERITY_LEVEL_LOW = 4,
  SEVERITY_LEVEL_INFORMATIONAL = 5,
  UNRECOGNIZED = -1,
}

export function severityLevelFromJSON(object: any): SeverityLevel {
  switch (object) {
    case 0:
    case "SEVERITY_LEVEL_UNSPECIFIED":
      return SeverityLevel.SEVERITY_LEVEL_UNSPECIFIED;
    case 1:
    case "SEVERITY_LEVEL_CRITICAL":
      return SeverityLevel.SEVERITY_LEVEL_CRITICAL;
    case 2:
    case "SEVERITY_LEVEL_HIGH":
      return SeverityLevel.SEVERITY_LEVEL_HIGH;
    case 3:
    case "SEVERITY_LEVEL_MEDIUM":
      return SeverityLevel.SEVERITY_LEVEL_MEDIUM;
    case 4:
    case "SEVERITY_LEVEL_LOW":
      return SeverityLevel.SEVERITY_LEVEL_LOW;
    case 5:
    case "SEVERITY_LEVEL_INFORMATIONAL":
      return SeverityLevel.SEVERITY_LEVEL_INFORMATIONAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SeverityLevel.UNRECOGNIZED;
  }
}

export function severityLevelToJSON(object: SeverityLevel): string {
  switch (object) {
    case SeverityLevel.SEVERITY_LEVEL_UNSPECIFIED:
      return "SEVERITY_LEVEL_UNSPECIFIED";
    case SeverityLevel.SEVERITY_LEVEL_CRITICAL:
      return "SEVERITY_LEVEL_CRITICAL";
    case SeverityLevel.SEVERITY_LEVEL_HIGH:
      return "SEVERITY_LEVEL_HIGH";
    case SeverityLevel.SEVERITY_LEVEL_MEDIUM:
      return "SEVERITY_LEVEL_MEDIUM";
    case SeverityLevel.SEVERITY_LEVEL_LOW:
      return "SEVERITY_LEVEL_LOW";
    case SeverityLevel.SEVERITY_LEVEL_INFORMATIONAL:
      return "SEVERITY_LEVEL_INFORMATIONAL";
    case SeverityLevel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum FindingStatus {
  FINDING_STATUS_SUBMITTED = 0,
  FINDING_STATUS_ACTIVE = 1,
  FINDING_STATUS_CONFIRMED = 2,
  FINDING_STATUS_PAID = 3,
  FINDING_STATUS_CLOSED = 4,
  UNRECOGNIZED = -1,
}

export function findingStatusFromJSON(object: any): FindingStatus {
  switch (object) {
    case 0:
    case "FINDING_STATUS_SUBMITTED":
      return FindingStatus.FINDING_STATUS_SUBMITTED;
    case 1:
    case "FINDING_STATUS_ACTIVE":
      return FindingStatus.FINDING_STATUS_ACTIVE;
    case 2:
    case "FINDING_STATUS_CONFIRMED":
      return FindingStatus.FINDING_STATUS_CONFIRMED;
    case 3:
    case "FINDING_STATUS_PAID":
      return FindingStatus.FINDING_STATUS_PAID;
    case 4:
    case "FINDING_STATUS_CLOSED":
      return FindingStatus.FINDING_STATUS_CLOSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return FindingStatus.UNRECOGNIZED;
  }
}

export function findingStatusToJSON(object: FindingStatus): string {
  switch (object) {
    case FindingStatus.FINDING_STATUS_SUBMITTED:
      return "FINDING_STATUS_SUBMITTED";
    case FindingStatus.FINDING_STATUS_ACTIVE:
      return "FINDING_STATUS_ACTIVE";
    case FindingStatus.FINDING_STATUS_CONFIRMED:
      return "FINDING_STATUS_CONFIRMED";
    case FindingStatus.FINDING_STATUS_PAID:
      return "FINDING_STATUS_PAID";
    case FindingStatus.FINDING_STATUS_CLOSED:
      return "FINDING_STATUS_CLOSED";
    case FindingStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TheoremStatus {
  /** THEOREM_STATUS_UNSPECIFIED - default theorem status. */
  THEOREM_STATUS_UNSPECIFIED = 0,
  /** THEOREM_STATUS_GRANT_PERIOD - theorem status during the grant period. */
  THEOREM_STATUS_GRANT_PERIOD = 1,
  /** THEOREM_STATUS_PROOF_PERIOD - theorem status during the proof period. */
  THEOREM_STATUS_PROOF_PERIOD = 2,
  /** THEOREM_STATUS_PASSED - theorem that has passed. */
  THEOREM_STATUS_PASSED = 3,
  /** THEOREM_STATUS_CLOSED - theorem that has closed. */
  THEOREM_STATUS_CLOSED = 4,
  UNRECOGNIZED = -1,
}

export function theoremStatusFromJSON(object: any): TheoremStatus {
  switch (object) {
    case 0:
    case "THEOREM_STATUS_UNSPECIFIED":
      return TheoremStatus.THEOREM_STATUS_UNSPECIFIED;
    case 1:
    case "THEOREM_STATUS_GRANT_PERIOD":
      return TheoremStatus.THEOREM_STATUS_GRANT_PERIOD;
    case 2:
    case "THEOREM_STATUS_PROOF_PERIOD":
      return TheoremStatus.THEOREM_STATUS_PROOF_PERIOD;
    case 3:
    case "THEOREM_STATUS_PASSED":
      return TheoremStatus.THEOREM_STATUS_PASSED;
    case 4:
    case "THEOREM_STATUS_CLOSED":
      return TheoremStatus.THEOREM_STATUS_CLOSED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TheoremStatus.UNRECOGNIZED;
  }
}

export function theoremStatusToJSON(object: TheoremStatus): string {
  switch (object) {
    case TheoremStatus.THEOREM_STATUS_UNSPECIFIED:
      return "THEOREM_STATUS_UNSPECIFIED";
    case TheoremStatus.THEOREM_STATUS_GRANT_PERIOD:
      return "THEOREM_STATUS_GRANT_PERIOD";
    case TheoremStatus.THEOREM_STATUS_PROOF_PERIOD:
      return "THEOREM_STATUS_PROOF_PERIOD";
    case TheoremStatus.THEOREM_STATUS_PASSED:
      return "THEOREM_STATUS_PASSED";
    case TheoremStatus.THEOREM_STATUS_CLOSED:
      return "THEOREM_STATUS_CLOSED";
    case TheoremStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ProofStatus {
  /** PROOF_STATUS_UNSPECIFIED - default proof status. */
  PROOF_STATUS_UNSPECIFIED = 0,
  /** PROOF_STATUS_HASH_LOCK_PERIOD - proof status during the creation period. */
  PROOF_STATUS_HASH_LOCK_PERIOD = 1,
  /** PROOF_STATUS_HASH_PROOF_PERIOD - proof status during the upload proof period. */
  PROOF_STATUS_HASH_PROOF_PERIOD = 2,
  /** PROOF_STATUS_PASSED - theorem that has passed. */
  PROOF_STATUS_PASSED = 3,
  /** PROOF_STATUS_FAILED - theorem that has failed. */
  PROOF_STATUS_FAILED = 4,
  /** PROOF_STATUS_TIMEOUT - theorem that has timeout. */
  PROOF_STATUS_TIMEOUT = 5,
  UNRECOGNIZED = -1,
}

export function proofStatusFromJSON(object: any): ProofStatus {
  switch (object) {
    case 0:
    case "PROOF_STATUS_UNSPECIFIED":
      return ProofStatus.PROOF_STATUS_UNSPECIFIED;
    case 1:
    case "PROOF_STATUS_HASH_LOCK_PERIOD":
      return ProofStatus.PROOF_STATUS_HASH_LOCK_PERIOD;
    case 2:
    case "PROOF_STATUS_HASH_PROOF_PERIOD":
      return ProofStatus.PROOF_STATUS_HASH_PROOF_PERIOD;
    case 3:
    case "PROOF_STATUS_PASSED":
      return ProofStatus.PROOF_STATUS_PASSED;
    case 4:
    case "PROOF_STATUS_FAILED":
      return ProofStatus.PROOF_STATUS_FAILED;
    case 5:
    case "PROOF_STATUS_TIMEOUT":
      return ProofStatus.PROOF_STATUS_TIMEOUT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ProofStatus.UNRECOGNIZED;
  }
}

export function proofStatusToJSON(object: ProofStatus): string {
  switch (object) {
    case ProofStatus.PROOF_STATUS_UNSPECIFIED:
      return "PROOF_STATUS_UNSPECIFIED";
    case ProofStatus.PROOF_STATUS_HASH_LOCK_PERIOD:
      return "PROOF_STATUS_HASH_LOCK_PERIOD";
    case ProofStatus.PROOF_STATUS_HASH_PROOF_PERIOD:
      return "PROOF_STATUS_HASH_PROOF_PERIOD";
    case ProofStatus.PROOF_STATUS_PASSED:
      return "PROOF_STATUS_PASSED";
    case ProofStatus.PROOF_STATUS_FAILED:
      return "PROOF_STATUS_FAILED";
    case ProofStatus.PROOF_STATUS_TIMEOUT:
      return "PROOF_STATUS_TIMEOUT";
    case ProofStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Program {
  programId: string;
  name: string;
  /** JSON by ProgramDetail */
  detail: string;
  adminAddress: string;
  status: ProgramStatus;
  createTime: Date | undefined;
}

export interface Finding {
  programId: string;
  findingId: string;
  title: string;
  description: string;
  proofOfConcept: string;
  /** hash(description + proof_of_concept + submitter) */
  findingHash: string;
  submitterAddress: string;
  severityLevel: SeverityLevel;
  status: FindingStatus;
  /** JSON by FindingDetail */
  detail: string;
  paymentHash: string;
  createTime: Date | undefined;
}

export interface ProgramFingerprint {
  programId: string;
  name: string;
  /** JSON by ProgramDetail */
  detail: string;
  adminAddress: string;
  status: ProgramStatus;
}

export interface FindingFingerprint {
  programId: string;
  findingId: string;
  title: string;
  /** hash(description + proof_of_concept + submitter) */
  findingHash: string;
  severityLevel: SeverityLevel;
  status: FindingStatus;
  /** JSON by FindingDetail */
  detail: string;
  paymentHash: string;
}

/** Theorem defines the core field members of an openmath theorem. */
export interface Theorem {
  /** id defines the unique id of the theorem. */
  id: string;
  /** title is the title of the theorem */
  title: string;
  /** description is the description of the theorem */
  description: string;
  /** code is a summary of the theorem */
  code: string;
  proofId: string;
  /** status defines the theorem status. */
  status: TheoremStatus;
  /** submit_time is the time of theorem submission. */
  submitTime:
    | Date
    | undefined;
  /** submit_time is the time of theorem submission. */
  grantEndTime:
    | Date
    | undefined;
  /** voting_start_time is the starting time to submit proof of a theorem. */
  proofStartTime: Date | undefined;
  proofEndTime:
    | Date
    | undefined;
  /** total_deposit is the total grant on the theorem. */
  totalGrant: Coin[];
  /** proposer is the address of the theorem submitter */
  proposer: string;
}

export interface Proof {
  theoremId: string;
  /** id defines the unique id of the proof. */
  id: string;
  /** proof_url is the proof data attached to the theorem stored in ipfs */
  proofContent: string;
  /** status defines the theorem status. */
  status: ProofStatus;
  /** submit_time is the time of proof submission. */
  submitTime:
    | Date
    | undefined;
  /** prover is the address of the proof submitter */
  prover: string;
  /**  */
  Deposit: Coin[];
}

/** Grant defines an amount granted by a grantor to an active theorem. */
export interface Grant {
  /** theorem_id defines the unique id of the theorem. */
  theoremsId: string;
  /** grantor defines the grant addresses. */
  grantor: string;
  /** amount to be deposited by the grantor. */
  amount: Coin[];
}

export interface Params {
  /** Minimum grant for a theorem to enter the proof period. */
  minGrant: Coin[];
  /** Maximum period for Shentu holders to grant on a theorem. Initial value: 2 weeks. */
  maxGrantPeriod:
    | Duration
    | undefined;
  /** Duration of the proof period. */
  proofPeriod:
    | Duration
    | undefined;
  /** Duration of the proof lock period. 10min */
  proofHashLockPeriod: Duration | undefined;
}

function createBaseProgram(): Program {
  return { programId: "", name: "", detail: "", adminAddress: "", status: 0, createTime: undefined };
}

export const Program = {
  encode(message: Program, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.programId !== "") {
      writer.uint32(10).string(message.programId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.detail !== "") {
      writer.uint32(26).string(message.detail);
    }
    if (message.adminAddress !== "") {
      writer.uint32(34).string(message.adminAddress);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    if (message.createTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createTime), writer.uint32(50).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Program {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProgram();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.programId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.detail = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.adminAddress = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.createTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Program {
    return {
      programId: isSet(object.programId) ? globalThis.String(object.programId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      detail: isSet(object.detail) ? globalThis.String(object.detail) : "",
      adminAddress: isSet(object.adminAddress) ? globalThis.String(object.adminAddress) : "",
      status: isSet(object.status) ? programStatusFromJSON(object.status) : 0,
      createTime: isSet(object.createTime) ? fromJsonTimestamp(object.createTime) : undefined,
    };
  },

  toJSON(message: Program): unknown {
    const obj: any = {};
    if (message.programId !== "") {
      obj.programId = message.programId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.detail !== "") {
      obj.detail = message.detail;
    }
    if (message.adminAddress !== "") {
      obj.adminAddress = message.adminAddress;
    }
    if (message.status !== 0) {
      obj.status = programStatusToJSON(message.status);
    }
    if (message.createTime !== undefined) {
      obj.createTime = message.createTime.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Program>, I>>(base?: I): Program {
    return Program.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Program>, I>>(object: I): Program {
    const message = createBaseProgram();
    message.programId = object.programId ?? "";
    message.name = object.name ?? "";
    message.detail = object.detail ?? "";
    message.adminAddress = object.adminAddress ?? "";
    message.status = object.status ?? 0;
    message.createTime = object.createTime ?? undefined;
    return message;
  },
};

function createBaseFinding(): Finding {
  return {
    programId: "",
    findingId: "",
    title: "",
    description: "",
    proofOfConcept: "",
    findingHash: "",
    submitterAddress: "",
    severityLevel: 0,
    status: 0,
    detail: "",
    paymentHash: "",
    createTime: undefined,
  };
}

export const Finding = {
  encode(message: Finding, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.programId !== "") {
      writer.uint32(10).string(message.programId);
    }
    if (message.findingId !== "") {
      writer.uint32(18).string(message.findingId);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.proofOfConcept !== "") {
      writer.uint32(42).string(message.proofOfConcept);
    }
    if (message.findingHash !== "") {
      writer.uint32(50).string(message.findingHash);
    }
    if (message.submitterAddress !== "") {
      writer.uint32(58).string(message.submitterAddress);
    }
    if (message.severityLevel !== 0) {
      writer.uint32(64).int32(message.severityLevel);
    }
    if (message.status !== 0) {
      writer.uint32(72).int32(message.status);
    }
    if (message.detail !== "") {
      writer.uint32(82).string(message.detail);
    }
    if (message.paymentHash !== "") {
      writer.uint32(90).string(message.paymentHash);
    }
    if (message.createTime !== undefined) {
      Timestamp.encode(toTimestamp(message.createTime), writer.uint32(98).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Finding {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFinding();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.programId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.findingId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.proofOfConcept = reader.string();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.findingHash = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.submitterAddress = reader.string();
          continue;
        case 8:
          if (tag !== 64) {
            break;
          }

          message.severityLevel = reader.int32() as any;
          continue;
        case 9:
          if (tag !== 72) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.detail = reader.string();
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.paymentHash = reader.string();
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.createTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Finding {
    return {
      programId: isSet(object.programId) ? globalThis.String(object.programId) : "",
      findingId: isSet(object.findingId) ? globalThis.String(object.findingId) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      proofOfConcept: isSet(object.proofOfConcept) ? globalThis.String(object.proofOfConcept) : "",
      findingHash: isSet(object.findingHash) ? globalThis.String(object.findingHash) : "",
      submitterAddress: isSet(object.submitterAddress) ? globalThis.String(object.submitterAddress) : "",
      severityLevel: isSet(object.severityLevel) ? severityLevelFromJSON(object.severityLevel) : 0,
      status: isSet(object.status) ? findingStatusFromJSON(object.status) : 0,
      detail: isSet(object.detail) ? globalThis.String(object.detail) : "",
      paymentHash: isSet(object.paymentHash) ? globalThis.String(object.paymentHash) : "",
      createTime: isSet(object.createTime) ? fromJsonTimestamp(object.createTime) : undefined,
    };
  },

  toJSON(message: Finding): unknown {
    const obj: any = {};
    if (message.programId !== "") {
      obj.programId = message.programId;
    }
    if (message.findingId !== "") {
      obj.findingId = message.findingId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.proofOfConcept !== "") {
      obj.proofOfConcept = message.proofOfConcept;
    }
    if (message.findingHash !== "") {
      obj.findingHash = message.findingHash;
    }
    if (message.submitterAddress !== "") {
      obj.submitterAddress = message.submitterAddress;
    }
    if (message.severityLevel !== 0) {
      obj.severityLevel = severityLevelToJSON(message.severityLevel);
    }
    if (message.status !== 0) {
      obj.status = findingStatusToJSON(message.status);
    }
    if (message.detail !== "") {
      obj.detail = message.detail;
    }
    if (message.paymentHash !== "") {
      obj.paymentHash = message.paymentHash;
    }
    if (message.createTime !== undefined) {
      obj.createTime = message.createTime.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Finding>, I>>(base?: I): Finding {
    return Finding.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Finding>, I>>(object: I): Finding {
    const message = createBaseFinding();
    message.programId = object.programId ?? "";
    message.findingId = object.findingId ?? "";
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.proofOfConcept = object.proofOfConcept ?? "";
    message.findingHash = object.findingHash ?? "";
    message.submitterAddress = object.submitterAddress ?? "";
    message.severityLevel = object.severityLevel ?? 0;
    message.status = object.status ?? 0;
    message.detail = object.detail ?? "";
    message.paymentHash = object.paymentHash ?? "";
    message.createTime = object.createTime ?? undefined;
    return message;
  },
};

function createBaseProgramFingerprint(): ProgramFingerprint {
  return { programId: "", name: "", detail: "", adminAddress: "", status: 0 };
}

export const ProgramFingerprint = {
  encode(message: ProgramFingerprint, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.programId !== "") {
      writer.uint32(10).string(message.programId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.detail !== "") {
      writer.uint32(26).string(message.detail);
    }
    if (message.adminAddress !== "") {
      writer.uint32(34).string(message.adminAddress);
    }
    if (message.status !== 0) {
      writer.uint32(40).int32(message.status);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ProgramFingerprint {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProgramFingerprint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.programId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.detail = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.adminAddress = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProgramFingerprint {
    return {
      programId: isSet(object.programId) ? globalThis.String(object.programId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      detail: isSet(object.detail) ? globalThis.String(object.detail) : "",
      adminAddress: isSet(object.adminAddress) ? globalThis.String(object.adminAddress) : "",
      status: isSet(object.status) ? programStatusFromJSON(object.status) : 0,
    };
  },

  toJSON(message: ProgramFingerprint): unknown {
    const obj: any = {};
    if (message.programId !== "") {
      obj.programId = message.programId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.detail !== "") {
      obj.detail = message.detail;
    }
    if (message.adminAddress !== "") {
      obj.adminAddress = message.adminAddress;
    }
    if (message.status !== 0) {
      obj.status = programStatusToJSON(message.status);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProgramFingerprint>, I>>(base?: I): ProgramFingerprint {
    return ProgramFingerprint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProgramFingerprint>, I>>(object: I): ProgramFingerprint {
    const message = createBaseProgramFingerprint();
    message.programId = object.programId ?? "";
    message.name = object.name ?? "";
    message.detail = object.detail ?? "";
    message.adminAddress = object.adminAddress ?? "";
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseFindingFingerprint(): FindingFingerprint {
  return {
    programId: "",
    findingId: "",
    title: "",
    findingHash: "",
    severityLevel: 0,
    status: 0,
    detail: "",
    paymentHash: "",
  };
}

export const FindingFingerprint = {
  encode(message: FindingFingerprint, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.programId !== "") {
      writer.uint32(10).string(message.programId);
    }
    if (message.findingId !== "") {
      writer.uint32(18).string(message.findingId);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.findingHash !== "") {
      writer.uint32(34).string(message.findingHash);
    }
    if (message.severityLevel !== 0) {
      writer.uint32(40).int32(message.severityLevel);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.detail !== "") {
      writer.uint32(58).string(message.detail);
    }
    if (message.paymentHash !== "") {
      writer.uint32(66).string(message.paymentHash);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): FindingFingerprint {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFindingFingerprint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.programId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.findingId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.findingHash = reader.string();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.severityLevel = reader.int32() as any;
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.detail = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.paymentHash = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FindingFingerprint {
    return {
      programId: isSet(object.programId) ? globalThis.String(object.programId) : "",
      findingId: isSet(object.findingId) ? globalThis.String(object.findingId) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      findingHash: isSet(object.findingHash) ? globalThis.String(object.findingHash) : "",
      severityLevel: isSet(object.severityLevel) ? severityLevelFromJSON(object.severityLevel) : 0,
      status: isSet(object.status) ? findingStatusFromJSON(object.status) : 0,
      detail: isSet(object.detail) ? globalThis.String(object.detail) : "",
      paymentHash: isSet(object.paymentHash) ? globalThis.String(object.paymentHash) : "",
    };
  },

  toJSON(message: FindingFingerprint): unknown {
    const obj: any = {};
    if (message.programId !== "") {
      obj.programId = message.programId;
    }
    if (message.findingId !== "") {
      obj.findingId = message.findingId;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.findingHash !== "") {
      obj.findingHash = message.findingHash;
    }
    if (message.severityLevel !== 0) {
      obj.severityLevel = severityLevelToJSON(message.severityLevel);
    }
    if (message.status !== 0) {
      obj.status = findingStatusToJSON(message.status);
    }
    if (message.detail !== "") {
      obj.detail = message.detail;
    }
    if (message.paymentHash !== "") {
      obj.paymentHash = message.paymentHash;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FindingFingerprint>, I>>(base?: I): FindingFingerprint {
    return FindingFingerprint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FindingFingerprint>, I>>(object: I): FindingFingerprint {
    const message = createBaseFindingFingerprint();
    message.programId = object.programId ?? "";
    message.findingId = object.findingId ?? "";
    message.title = object.title ?? "";
    message.findingHash = object.findingHash ?? "";
    message.severityLevel = object.severityLevel ?? 0;
    message.status = object.status ?? 0;
    message.detail = object.detail ?? "";
    message.paymentHash = object.paymentHash ?? "";
    return message;
  },
};

function createBaseTheorem(): Theorem {
  return {
    id: "0",
    title: "",
    description: "",
    code: "",
    proofId: "",
    status: 0,
    submitTime: undefined,
    grantEndTime: undefined,
    proofStartTime: undefined,
    proofEndTime: undefined,
    totalGrant: [],
    proposer: "",
  };
}

export const Theorem = {
  encode(message: Theorem, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "0") {
      writer.uint32(8).uint64(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.code !== "") {
      writer.uint32(34).string(message.code);
    }
    if (message.proofId !== "") {
      writer.uint32(42).string(message.proofId);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.submitTime !== undefined) {
      Timestamp.encode(toTimestamp(message.submitTime), writer.uint32(58).fork()).ldelim();
    }
    if (message.grantEndTime !== undefined) {
      Timestamp.encode(toTimestamp(message.grantEndTime), writer.uint32(66).fork()).ldelim();
    }
    if (message.proofStartTime !== undefined) {
      Timestamp.encode(toTimestamp(message.proofStartTime), writer.uint32(74).fork()).ldelim();
    }
    if (message.proofEndTime !== undefined) {
      Timestamp.encode(toTimestamp(message.proofEndTime), writer.uint32(82).fork()).ldelim();
    }
    for (const v of message.totalGrant) {
      Coin.encode(v!, writer.uint32(90).fork()).ldelim();
    }
    if (message.proposer !== "") {
      writer.uint32(98).string(message.proposer);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Theorem {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTheorem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = longToString(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.code = reader.string();
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.proofId = reader.string();
          continue;
        case 6:
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.submitTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.grantEndTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.proofStartTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.proofEndTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 11:
          if (tag !== 90) {
            break;
          }

          message.totalGrant.push(Coin.decode(reader, reader.uint32()));
          continue;
        case 12:
          if (tag !== 98) {
            break;
          }

          message.proposer = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Theorem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "0",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      proofId: isSet(object.proofId) ? globalThis.String(object.proofId) : "",
      status: isSet(object.status) ? theoremStatusFromJSON(object.status) : 0,
      submitTime: isSet(object.submitTime) ? fromJsonTimestamp(object.submitTime) : undefined,
      grantEndTime: isSet(object.grantEndTime) ? fromJsonTimestamp(object.grantEndTime) : undefined,
      proofStartTime: isSet(object.proofStartTime) ? fromJsonTimestamp(object.proofStartTime) : undefined,
      proofEndTime: isSet(object.proofEndTime) ? fromJsonTimestamp(object.proofEndTime) : undefined,
      totalGrant: globalThis.Array.isArray(object?.totalGrant)
        ? object.totalGrant.map((e: any) => Coin.fromJSON(e))
        : [],
      proposer: isSet(object.proposer) ? globalThis.String(object.proposer) : "",
    };
  },

  toJSON(message: Theorem): unknown {
    const obj: any = {};
    if (message.id !== "0") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.proofId !== "") {
      obj.proofId = message.proofId;
    }
    if (message.status !== 0) {
      obj.status = theoremStatusToJSON(message.status);
    }
    if (message.submitTime !== undefined) {
      obj.submitTime = message.submitTime.toISOString();
    }
    if (message.grantEndTime !== undefined) {
      obj.grantEndTime = message.grantEndTime.toISOString();
    }
    if (message.proofStartTime !== undefined) {
      obj.proofStartTime = message.proofStartTime.toISOString();
    }
    if (message.proofEndTime !== undefined) {
      obj.proofEndTime = message.proofEndTime.toISOString();
    }
    if (message.totalGrant?.length) {
      obj.totalGrant = message.totalGrant.map((e) => Coin.toJSON(e));
    }
    if (message.proposer !== "") {
      obj.proposer = message.proposer;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Theorem>, I>>(base?: I): Theorem {
    return Theorem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Theorem>, I>>(object: I): Theorem {
    const message = createBaseTheorem();
    message.id = object.id ?? "0";
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.code = object.code ?? "";
    message.proofId = object.proofId ?? "";
    message.status = object.status ?? 0;
    message.submitTime = object.submitTime ?? undefined;
    message.grantEndTime = object.grantEndTime ?? undefined;
    message.proofStartTime = object.proofStartTime ?? undefined;
    message.proofEndTime = object.proofEndTime ?? undefined;
    message.totalGrant = object.totalGrant?.map((e) => Coin.fromPartial(e)) || [];
    message.proposer = object.proposer ?? "";
    return message;
  },
};

function createBaseProof(): Proof {
  return { theoremId: "0", id: "", proofContent: "", status: 0, submitTime: undefined, prover: "", Deposit: [] };
}

export const Proof = {
  encode(message: Proof, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.theoremId !== "0") {
      writer.uint32(8).uint64(message.theoremId);
    }
    if (message.id !== "") {
      writer.uint32(18).string(message.id);
    }
    if (message.proofContent !== "") {
      writer.uint32(26).string(message.proofContent);
    }
    if (message.status !== 0) {
      writer.uint32(32).int32(message.status);
    }
    if (message.submitTime !== undefined) {
      Timestamp.encode(toTimestamp(message.submitTime), writer.uint32(42).fork()).ldelim();
    }
    if (message.prover !== "") {
      writer.uint32(50).string(message.prover);
    }
    for (const v of message.Deposit) {
      Coin.encode(v!, writer.uint32(58).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Proof {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProof();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.theoremId = longToString(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.id = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.proofContent = reader.string();
          continue;
        case 4:
          if (tag !== 32) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.submitTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.prover = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.Deposit.push(Coin.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Proof {
    return {
      theoremId: isSet(object.theoremId) ? globalThis.String(object.theoremId) : "0",
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      proofContent: isSet(object.proofContent) ? globalThis.String(object.proofContent) : "",
      status: isSet(object.status) ? proofStatusFromJSON(object.status) : 0,
      submitTime: isSet(object.submitTime) ? fromJsonTimestamp(object.submitTime) : undefined,
      prover: isSet(object.prover) ? globalThis.String(object.prover) : "",
      Deposit: globalThis.Array.isArray(object?.Deposit) ? object.Deposit.map((e: any) => Coin.fromJSON(e)) : [],
    };
  },

  toJSON(message: Proof): unknown {
    const obj: any = {};
    if (message.theoremId !== "0") {
      obj.theoremId = message.theoremId;
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.proofContent !== "") {
      obj.proofContent = message.proofContent;
    }
    if (message.status !== 0) {
      obj.status = proofStatusToJSON(message.status);
    }
    if (message.submitTime !== undefined) {
      obj.submitTime = message.submitTime.toISOString();
    }
    if (message.prover !== "") {
      obj.prover = message.prover;
    }
    if (message.Deposit?.length) {
      obj.Deposit = message.Deposit.map((e) => Coin.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Proof>, I>>(base?: I): Proof {
    return Proof.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Proof>, I>>(object: I): Proof {
    const message = createBaseProof();
    message.theoremId = object.theoremId ?? "0";
    message.id = object.id ?? "";
    message.proofContent = object.proofContent ?? "";
    message.status = object.status ?? 0;
    message.submitTime = object.submitTime ?? undefined;
    message.prover = object.prover ?? "";
    message.Deposit = object.Deposit?.map((e) => Coin.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGrant(): Grant {
  return { theoremsId: "0", grantor: "", amount: [] };
}

export const Grant = {
  encode(message: Grant, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.theoremsId !== "0") {
      writer.uint32(8).uint64(message.theoremsId);
    }
    if (message.grantor !== "") {
      writer.uint32(18).string(message.grantor);
    }
    for (const v of message.amount) {
      Coin.encode(v!, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Grant {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGrant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.theoremsId = longToString(reader.uint64() as Long);
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.grantor = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.amount.push(Coin.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Grant {
    return {
      theoremsId: isSet(object.theoremsId) ? globalThis.String(object.theoremsId) : "0",
      grantor: isSet(object.grantor) ? globalThis.String(object.grantor) : "",
      amount: globalThis.Array.isArray(object?.amount) ? object.amount.map((e: any) => Coin.fromJSON(e)) : [],
    };
  },

  toJSON(message: Grant): unknown {
    const obj: any = {};
    if (message.theoremsId !== "0") {
      obj.theoremsId = message.theoremsId;
    }
    if (message.grantor !== "") {
      obj.grantor = message.grantor;
    }
    if (message.amount?.length) {
      obj.amount = message.amount.map((e) => Coin.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Grant>, I>>(base?: I): Grant {
    return Grant.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Grant>, I>>(object: I): Grant {
    const message = createBaseGrant();
    message.theoremsId = object.theoremsId ?? "0";
    message.grantor = object.grantor ?? "";
    message.amount = object.amount?.map((e) => Coin.fromPartial(e)) || [];
    return message;
  },
};

function createBaseParams(): Params {
  return { minGrant: [], maxGrantPeriod: undefined, proofPeriod: undefined, proofHashLockPeriod: undefined };
}

export const Params = {
  encode(message: Params, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.minGrant) {
      Coin.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    if (message.maxGrantPeriod !== undefined) {
      Duration.encode(message.maxGrantPeriod, writer.uint32(18).fork()).ldelim();
    }
    if (message.proofPeriod !== undefined) {
      Duration.encode(message.proofPeriod, writer.uint32(26).fork()).ldelim();
    }
    if (message.proofHashLockPeriod !== undefined) {
      Duration.encode(message.proofHashLockPeriod, writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Params {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.minGrant.push(Coin.decode(reader, reader.uint32()));
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.maxGrantPeriod = Duration.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.proofPeriod = Duration.decode(reader, reader.uint32());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.proofHashLockPeriod = Duration.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      minGrant: globalThis.Array.isArray(object?.minGrant) ? object.minGrant.map((e: any) => Coin.fromJSON(e)) : [],
      maxGrantPeriod: isSet(object.maxGrantPeriod) ? Duration.fromJSON(object.maxGrantPeriod) : undefined,
      proofPeriod: isSet(object.proofPeriod) ? Duration.fromJSON(object.proofPeriod) : undefined,
      proofHashLockPeriod: isSet(object.proofHashLockPeriod)
        ? Duration.fromJSON(object.proofHashLockPeriod)
        : undefined,
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.minGrant?.length) {
      obj.minGrant = message.minGrant.map((e) => Coin.toJSON(e));
    }
    if (message.maxGrantPeriod !== undefined) {
      obj.maxGrantPeriod = Duration.toJSON(message.maxGrantPeriod);
    }
    if (message.proofPeriod !== undefined) {
      obj.proofPeriod = Duration.toJSON(message.proofPeriod);
    }
    if (message.proofHashLockPeriod !== undefined) {
      obj.proofHashLockPeriod = Duration.toJSON(message.proofHashLockPeriod);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.minGrant = object.minGrant?.map((e) => Coin.fromPartial(e)) || [];
    message.maxGrantPeriod = (object.maxGrantPeriod !== undefined && object.maxGrantPeriod !== null)
      ? Duration.fromPartial(object.maxGrantPeriod)
      : undefined;
    message.proofPeriod = (object.proofPeriod !== undefined && object.proofPeriod !== null)
      ? Duration.fromPartial(object.proofPeriod)
      : undefined;
    message.proofHashLockPeriod = (object.proofHashLockPeriod !== undefined && object.proofHashLockPeriod !== null)
      ? Duration.fromPartial(object.proofHashLockPeriod)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000).toString();
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (globalThis.Number(t.seconds) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToString(long: Long) {
  return long.toString();
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
